### ISSUE TITLE
Change Requested for AppCenter: Inaccurate .desktop data

### ISSUE THREAD

**Issue by cassidyjames** [bartzaalberg/recipes#1]
https://github.com/bartzaalberg/recipes/blob/65e9a6f873029f20fe3cb1f05e8a3ee98094afc6/data/com.github.bartzaalberg.recipes.desktop#L4

https://github.com/bartzaalberg/recipes/blob/65e9a6f873029f20fe3cb1f05e8a3ee98094afc6/data/com.github.bartzaalberg.recipes.desktop#L11

**Comment by unbelievableflavour** [comment]
Fixed
