### ISSUE TITLE
Add capability to translate recipes title in overview

### ISSUE THREAD

**Issue by NathanBnm** [bartzaalberg/recipes#16]
This is actually impossible with the `recipes.json` file configuration.

**Comment by unbelievableflavour** [comment]
I noticed. Any proposition on how I could achieve this? I though of maybe changing the recipes.json file like this:
```
{
        "id": "figs_with_goat_cheese",
        "title": {
           "en": "Figs with goat cheese",
           "nl": "Vijgen met geiten kaas",
        },
        "thumbnail": "https://static.ah.nl/static/recepten/img_011299_890x594_JPG.jpg",
        "author": "Charlotte Brussee",
        "languages": ["en", "fr", "nl"]
    },

**Comment by NathanBnm** [comment]
Yes I don't know how to do that in a different way, maybe it's a good idea 👍

**Comment by unbelievableflavour** [comment]
I created a new-recipes.json for now. Will change that back to recipe.json in a week or so so that most people are migrated. It's in master and should be released soon.

**Comment by NathanBnm** [comment]
Okay! Tell me if you want me to translate it before a new update :smile:

**Comment by unbelievableflavour** [comment]
I picked your translations from the image descriptions :)

**Comment by NathanBnm** [comment]
That's should be good so

**Comment by unbelievableflavour** [comment]
@NathanBnm I did add some lines to https://github.com/bartzaalberg/recipes/blob/master/recipes/your_own_recipe/recipe_en.md that english translation is necessary as fallback. Maybe you could add that to recipe_fr too?

**Comment by unbelievableflavour** [comment]
It's been released.
Closing this. Please reopen if not working.

**Comment by NathanBnm** [comment]
Actually the recipes title translations aren't working. But everything else is good :+1:

Here is a screenshot:
![image](https://user-images.githubusercontent.com/45366162/54339202-6c41b500-4634-11e9-83cf-9ac927598eae.png)

**Comment by unbelievableflavour** [comment]
Ok, so now you always get Dutch translations.. Thats not good. Will look at that tonight.

**Comment by unbelievableflavour** [comment]
Bug fix is in master. Accidentaly hardcoded NL

**Comment by NathanBnm** [comment]
Okay great
