### ISSUE TITLE
Add a search input to headerbar

### ISSUE THREAD

**Issue by NathanBnm** [bartzaalberg/recipes#17]
It can be useful to search for recipes without scrolling all the overview. Especially if new recipes are added later. I was thinking to a centred search input like the "Fondo" app in AppCenter.

**Comment by unbelievableflavour** [comment]
Yes, Will do!

**Comment by unbelievableflavour** [comment]
I added a search to master, haven't styled it yet. I will do that later.

**Comment by unbelievableflavour** [comment]
Done, it's been released. Styling will be done probably in next release.

**Comment by unbelievableflavour** [comment]
New styling has also been released.
Closing this. Please reopen if not working.
