### ISSUE TITLE
Change Requested for AppCenter: Branding

### ISSUE THREAD

**Issue by cassidyjames** [bartzaalberg/recipes#2]
We recommend not including the platform name (elementary OS) in AppData, because for users coming across the app, all curated apps in AppCenter are made for elementary OS. But if you do include it for some reason, be sure it follows the guidelines at elementary.io/brand. In this case, "elementary" is *always* lower-case.

https://github.com/bartzaalberg/recipes/blob/65e9a6f873029f20fe3cb1f05e8a3ee98094afc6/data/com.github.bartzaalberg.recipes.appdata.xml#L8

**Comment by unbelievableflavour** [comment]
Fixed
