### ISSUE TITLE
Change Requested for AppCenter: OARS data

### ISSUE THREAD

**Issue by cassidyjames** [bartzaalberg/recipes#3]
Apps submitted to AppCenter require OARS data in their AppData. You can generate it at https://hughsie.github.io/oars/generate.html

In particular, due to these:

https://github.com/bartzaalberg/recipes/blob/65e9a6f873029f20fe3cb1f05e8a3ee98094afc6/src/RecipeFileManager.vala#L44-L47

https://github.com/bartzaalberg/recipes/blob/65e9a6f873029f20fe3cb1f05e8a3ee98094afc6/src/RecipeFileManager.vala#L94-L97

…be sure to include at least `social-info: mild`.

**Comment by unbelievableflavour** [comment]
Thnx. Added it.
