### ISSUE TITLE
Change Requested for AppCenter: Unneeded pkexec policy?

### ISSUE THREAD

**Issue by cassidyjames** [bartzaalberg/recipes#4]
Perhaps I'm missing something, but I don't believe the included pkexec policy is needed for a recipes app. 

https://github.com/bartzaalberg/recipes/blob/65e9a6f873029f20fe3cb1f05e8a3ee98094afc6/data/com.github.bartzaalberg.recipes.pkexec.policy

**Comment by unbelievableflavour** [comment]
Oh your right. That's not needed. Sorry i thought i already deleted that!

**Comment by unbelievableflavour** [comment]
Removed it.
