### ISSUE TITLE
AppData colors not contrast compliant

### ISSUE THREAD

**Issue by cassidyjames** [bartzaalberg/recipes#7]
It looks like the foreground and background colors in your AppData do not have good contrast.

![image](https://user-images.githubusercontent.com/611168/51576278-c911c200-1e72-11e9-9bae-ad92c050e8bf.png)

The result is that it's almost illegible.

![image](https://user-images.githubusercontent.com/611168/51576296-dcbd2880-1e72-11e9-8705-5cc97c0c8f38.png)

**Comment by unbelievableflavour** [comment]
Is 1 A fine? I try to stick to the color of the application. Also why isn't it shown yet in Appcenter? It has a green button on https://developer.elementary.io/dashboard.

**Comment by bartzaalberg** [comment]
If it's fine. Please close, this is in latest release.

**Comment by cassidyjames** [comment]
@bartzaalberg sometimes AppCenter takes a bit longer to download the updated metadata. The newer version with the higher contrast has been released now as well!
